### ISSUE TITLE
Use libuv for cross-platform uniform code for ports on Windows and othe OS

### ISSUE THREAD

**Issue by as-shura** [zenomt/rtmfp-cpp#14]
Hi I was wondering why don't you use something like https://github.com/ithewei/libhv.

You said you don't have any windows networking programming XP. With this framework you write your code once and it works on all platform. With one rock you hit all birds.

It seems that it has something similar to what you did with Event Loop.

Best Regards

**Comment by zenomt** [comment]
> Hi I was wondering why don't you use something like https://github.com/ithewei/libhv

i wanted this library to have no external dependencies (except for OpenSSL, which isn't actually required -- you can make adapters for other crypto libraries with not much effort using the OpenSSL version as a guide).

i'm supplying simple example RunLoops and Platform Adapters that meet my own needs, but these also don't need to be used. the intent is that, by supplying appropriate adapters, you can use this library with _any_ host application, no matter what networking/event library/framework you're using (libhv, Boost, NSRunLoop/CFRunLoop, my RunLoops, or something bespoke for your application).

as i've mentioned, i'd be happy to link to other Platform Adapters (and i'd be happy to link to other Crypto Adapters too) if people in the community develop them. however, i'm not going to convert the supplied samples in this library to use an external dependency.
