### ISSUE TITLE
Cannot compile on Linux Fedora 40

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [zenomt/rtmfp-cpp#16]
here is the error log:
g++ -Os -Wall -pedantic -std=c++11   -c -o src/URIParse.o src/URIParse.cpp
In file included from src/URIParse.cpp:9:
src/../include/rtmfp/Hex.hpp:15:62: error: ‘uint8_t’ was not declared in this scope
   15 |         static void print(const char *msg, const std::vector<uint8_t> &bytes);
      |                                                              ^~~~~~~
src/../include/rtmfp/Hex.hpp:8:1: note: ‘uint8_t’ is defined in header ‘<cstdint>’; this is probably fixable by adding ‘#include <cstdint>’
    7 | #include <vector>
  +++ |+#include <cstdint>
    8 |
src/../include/rtmfp/Hex.hpp:15:69: error: template argument 1 is invalid
   15 |         static void print(const char *msg, const std::vector<uint8_t> &bytes);
      |                                                                     ^
src/../include/rtmfp/Hex.hpp:15:69: error: template argument 2 is invalid
src/../include/rtmfp/Hex.hpp:22:53: error: ‘uint8_t’ was not declared in this scope
   22 |         static std::string encode(const std::vector<uint8_t> &bytes);
      |                                                     ^~~~~~~
src/../include/rtmfp/Hex.hpp:22:53: note: ‘uint8_t’ is defined in header ‘<cstdint>’; this is probably fixable by adding ‘#include <cstdint>’
src/../include/rtmfp/Hex.hpp:22:60: error: template argument 1 is invalid
   22 |         static std::string encode(const std::vector<uint8_t> &bytes);
      |                                                            ^
src/../include/rtmfp/Hex.hpp:22:60: error: template argument 2 is invalid
src/../include/rtmfp/Hex.hpp:24:57: error: ‘uint8_t’ was not declared in this scope
   24 |         static bool decode(const char *hex, std::vector<uint8_t> &dst);
      |                                                         ^~~~~~~
src/../include/rtmfp/Hex.hpp:24:57: note: ‘uint8_t’ is defined in header ‘<cstdint>’; this is probably fixable by adding ‘#include <cstdint>’
src/../include/rtmfp/Hex.hpp:24:64: error: template argument 1 is invalid
   24 |         static bool decode(const char *hex, std::vector<uint8_t> &dst);
      |                                                                ^
src/../include/rtmfp/Hex.hpp:24:64: error: template argument 2 is invalid
src/URIParse.cpp: In static member function ‘static std::string com::zenomt::URIParse::percentDecode(const std::string&)’:
src/URIParse.cpp:226:38: error: ‘uint8_t’ was not declared in this scope
  226 |                         rv.push_back(uint8_t(b));
      |                                      ^~~~~~~
src/URIParse.cpp:11:1: note: ‘uint8_t’ is defined in header ‘<cstdint>’; this is probably fixable by adding ‘#include <cstdint>’
   10 | #include "../include/rtmfp/URIParse.hpp"
  +++ |+#include <cstdint>
   11 |
make: *** [<builtin>: src/URIParse.o] Error 

gcc 14.1.1

Thanks

**Comment by zenomt** [comment]
thanks. i'll look at this tonight.

**Comment by zenomt** [comment]
i don't have ready access to a Fedora 40 system (nor a desire to install a VM). rather than playing whack-a-mole, can you tell me if you get any other compile errors after adding an
```
#include <cstdint>
```
to include/rtmfp/Hex.hpp, just above the include for `<string>`? i'd like to fix all the problems at once. :)

**Comment by zenomt** [comment]
in installed a Fedora 40 VM and replicated your build error with g++ 14.1.1. the only error was a missing `#include <cstdint>` in Hex.hpp. https://github.com/zenomt/rtmfp-cpp/commit/9c53bde974e6463537a4e5573a548e59eb45786c should fix that.

please confirm the problem is fixed for you, and i'll close this issue.

**Comment by ROBERT-MCDOWELL** [comment]
I confirm it compiles perfectly now. man thanks!
